version: '3'
services:
  back:
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: apps/back/Dockerfile
    env_file:
      - apps/back/docker.env
    volumes:
      - ./apps/back/:/usr/app/apps/back/
      - ./packages/contract:/usr/app/packages/contract
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c  "npm run studio-all & npm run dev-all"
  front:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    init: true
    volumes:
      - ./apps/front/:/usr/app/apps/front/
      - ./packages/contract:/usr/app/packages/contract
      - /usr/app/apps/front/node_modules
    ports:
      - '4200:4200'
    depends_on:
      - back
    command: npm run dev-all
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./data:/var/lib/postgresql/data
