# fly.toml app configuration file generated for cine-map-back-dawn-field-8435 on 2024-04-28T12:54:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cine-map-back'
primary_region = 'cdg'

[build]
  dockerfile = './apps/back/Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
