/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreatemapImport } from './routes/create_map'
import { Route as IndexImport } from './routes/index'
import { Route as MoviesMovieIdImport } from './routes/movies.$movieId'

// Create/Update Routes

const CreatemapRoute = CreatemapImport.update({
  path: '/create_map',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesMovieIdRoute = MoviesMovieIdImport.update({
  path: '/movies/$movieId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create_map': {
      preLoaderRoute: typeof CreatemapImport
      parentRoute: typeof rootRoute
    }
    '/movies/$movieId': {
      preLoaderRoute: typeof MoviesMovieIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CreatemapRoute,
  MoviesMovieIdRoute,
])

/* prettier-ignore-end */
